apiVersion: v1
kind: Service
metadata:
  name: hiremeupfrontend-service
spec:
  selector:
    app: hiremeupfrontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP

